# Generated by Django 5.1.3 on 2024-11-21 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('nome_setor', models.CharField(max_length=255)),
                ('prioridade', models.CharField(choices=[('Baixo', 'Baixo'), ('Media', 'Media'), ('Alto', 'Alta')], max_length=10)),
                ('data_cadastro', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('A fazer', 'Fazer'), ('Fazendo', 'Fazendo'), ('Pronto', 'Pronto')], default='A fazer', max_length=10)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_usuario', to='app.usuario')),
            ],
        ),
    ]
